version: '3'

networks:
  db:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: laravel
    ports:
      - "40000:3306"
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "40001:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    networks:
      - db
